### ISSUE TITLE
Current build doesn't work

### ISSUE THREAD

**Issue by jbnl** [kwash-dev/kwagsh#1]
Receiving this error all over the place: /coinbuild/kwagsh/src/CryptoNoteCore/../CryptoNoteConfig.h:30:68: error: ‘DIFFICULTY_TARGET’ was not declared in this scope

Please update your code so we can rebuild your binaries.

**Comment by kwash-dev** [comment]
working on it, to complete all. it will come up soonest

**Comment by kwash-dev** [comment]
Code updated now you can build
