### ISSUE TITLE
kwagsh v1.4.7.1 Segmentation fault

### ISSUE THREAD

**Issue by getpool** [kwash-dev/Kwagsh#1]
2018-Jun-07 11:42:57.898413 INFO    kwagsh v1.4.7.1 (ce54392)
2018-Jun-07 11:42:57.898682 INFO    Module folder: ./kwagshd
2018-Jun-07 11:42:57.901223 INFO    Initializing p2p server...
2018-Jun-07 11:42:57.902281 INFO    Network: 5be4a199-1881-8b1e-3a19-3a2787a9bde3

2018-Jun-07 11:41:24.684111 INFO     expected difficulty: 686110074
2018-Jun-07 11:41:25.969042 INFO    [173.249.48.221:59087 INC] Sync data returned unknown top block: 40061 -> 41549 [1488 blocks (2 days) behind] 
2018-Jun-07 11:41:25.969042 INFO    SYNCHRONIZATION started
2018-Jun-07 11:41:27.015169 INFO    Block with id: 0822a63706bbe2e6e359324c320230ecd1b1641b0568a6e361eadc3bf5e982e5
2018-Jun-07 11:41:27.015169 INFO     for alternative chain, have not enough proof of work: af4eeea0dac2b73ae49ee8fd9deb07de54c2ceee33fdd91ff7cdad93ee1e0000
2018-Jun-07 11:41:27.015169 INFO     expected difficulty: 686110074
2018-Jun-07 11:41:28.868814 INFO    [81.2.240.84:25386 OUT] Sync data returned unknown top block: 40061 -> 41549 [1488 blocks (2 days) behind] 
2018-Jun-07 11:41:28.868814 INFO    SYNCHRONIZATION started
Segmentation fault

**Comment by laugh26** [comment]
You need the new wallet
